apiVersion: apps/v1
kind: Deployment
metadata:
  name: web-b
spec:
  replicas: 1
  selector:
    matchLabels:
      app: web-b
  template:
    metadata:
      labels:
        app: web-b
    spec:
      containers:
        - name: nginx
          image: nginx:1.27
          ports:
            - containerPort: 80
          resources:
            requests: { cpu: 50m, memory: 64Mi }
            limits: { cpu: 200m, memory: 128Mi }
---
apiVersion: v1
kind: Service
metadata:
  name: web-b
spec:
  selector:
    app: web-b
  ports:
    - port: 80
      targetPort: 80
