apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: web-a
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: lab
  source:
    repoURL: https://github.com/kishoreala/gitops-argocd.git
    targetRevision: main
    path: workloads/web-a
  destination:
    server: https://kubernetes.default.svc
    namespace: lab-web-a
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
