apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: team-a-bad-destination
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: team-a
  source:
    repoURL: https://github.com/kishoreala/gitops-argocd.git
    targetRevision: main
    path: scenarios/03-appproject-tenancy/manifests-ok
  destination:
    server: https://kubernetes.default.svc
    namespace: kube-system
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
